import PAGE from './index.html';
import CSS from './styles.css';
import CLIENT from './app.js';
import FROZEN from './research-baseline.json';
import LIBRARY_DEMO from './library-demo.json';
import CURRENT_DAILY_PLAN from './current-daily-plan.json';
import HISTORICAL_DAILY_RESULTS from './historical-daily-results.json';
import MODULAR_DAILY_RESULTS from './modular-daily-results.json';
import DAILY_REFINEMENT from './daily-refinement.json';
export {PAGE,CSS,CLIENT,FROZEN,LIBRARY_DEMO,CURRENT_DAILY_PLAN,HISTORICAL_DAILY_RESULTS,MODULAR_DAILY_RESULTS,DAILY_REFINEMENT};
