import {describeMinuteRule} from './minute-rules.mjs';
import {minuteQuality} from './minute-quality.mjs';
import spy from '../demo-data/SPY-1Min-snapshot.json';
import hkSnapshot from '../demo-data/HK-1Min-snapshot.json';
import cnSnapshot from '../demo-data/CN-1Min-snapshot.json';
import {runMinuteResearch,LIBRARY_STRATEGIES} from './minute-library.mjs';
import {validateMinuteSnapshot,minuteValidation} from './minute-validation.mjs';
export function createMinuteLab(root,onReport){
 const snapshots={US:{market:'US',symbol:'SPY',timeframe:'1Min',sample_kind:'historical',source:'Yahoo Finance Chart 公开历史快照',bars:spy.bars},HK:hkSnapshot,CN:cnSnapshot};let market='US',type='opening_range';
 root.innerHTML=`<h2>用历史样本重新回测</h2><p>本地计算，无需登录，也不会下单。修改参数后，回放、决策与结果一起更新；也可导入自己的真实分钟行情 JSON。</p><form class="form-grid"><label>策略预算<input name="budget" type="number" min="100" max="100000" value="2000" required></label><label>单边成本（基点）<input name="cost_bps" type="number" min="0" max="100" value="10" required></label><label>开盘观察分钟<input name="opening_minutes" type="number" min="5" max="60" value="15" required></label><label>触发下限（基点）<input name="threshold_bps" type="number" min="0" max="200" value="20" required></label><label data-adaptive>动量窗口<input name="lookback" type="number" min="5" max="120" value="20" required></label><label data-adaptive>成交量倍数<input name="volume_multiplier" type="number" min="0.1" max="10" step="0.1" value="1.2" required></label><label data-adaptive>波动阈值倍数<input name="volatility_multiplier" type="number" min="0.1" max="10" step="0.1" value="2" required></label><label>导入分钟快照（仅在本机读取）<input name="file" type="file" accept=".json,application/json"></label><button class="primary" type="submit">重新回测当前样本</button></form><p class="notice" data-lab-status role="status"></p><details><summary>开发段、检验段与双倍成本</summary><p>按交易日先后以 60% / 40% 切分，参数固定，不使用后段选择参数；每段独立起始资金与预热，不能拼接为完整曲线。短样本只测试流程。</p><div data-lab-validation></div></details>`;
 const form=root.querySelector('form'),status=root.querySelector('[data-lab-status]');
 function renderValidation(v){
  const box=root.querySelector('[data-lab-validation]');box.replaceChildren();const note=document.createElement('p');note.textContent=v.status;box.append(note);const table=document.createElement('table'),head=document.createElement('tr');for(const label of ['区间 / 情景','交易日','收益','最大回撤','成交笔数','成本']){const th=document.createElement('th');th.textContent=label;head.append(th);}table.append(head);
  for(const [key,label] of [['full','完整样本'],['development','前 60%：开发段'],['holdout','后 40%：检验段'],['double_cost','双倍交易成本']]){const x=v[key],tr=document.createElement('tr');for(const value of [label,x?.days??'不足',Number.isFinite(x?.return_pct)?x.return_pct.toFixed(3)+'%':'未计算',Number.isFinite(x?.drawdown_pct)?x.drawdown_pct.toFixed(3)+'%':'未计算',x?.trades??'—',Number.isFinite(x?.cost)?x.cost.toFixed(2):'—']){const td=document.createElement('td');td.textContent=value;tr.append(td);}table.append(tr);}const scroll=document.createElement('div');scroll.className='table-scroll';scroll.append(table);box.append(scroll);
 }
 function info(){const s=snapshots[market];status.textContent=`当前样本：${market} · ${s.symbol} · ${s.source} · ${s.bars.length} 根 · ${s.bars[0].t} 至 ${s.bars.at(-1).t} · ${s.sample_kind==='historical'?'真实历史（来源由提供者声明，请核对授权与数据质量）':'合成演示'}`;}
 form.onsubmit=async e=>{e.preventDefault();const button=form.querySelector('button');button.disabled=true;try{let s=snapshots[market];const file=form.elements.file.files[0];if(file){if(file.size>20000000)throw Error('快照须小于 20 MB');s=validateMinuteSnapshot(JSON.parse(await file.text()));if(s.market!==market)throw Error('先选择与导入快照一致的市场');snapshots[market]=s;form.elements.file.value='';}const params=Object.fromEntries([...new FormData(form)].filter(([k])=>k!=='file').map(([k,v])=>[k,Number(v)]));const r=runMinuteResearch(s.bars,{...params,market,symbol:s.symbol,type});const definition=LIBRARY_STRATEGIES.find(x=>x.id===type);const validation=minuteValidation(s,{...params,type});onReport({...r,validation,dataQuality:minuteQuality(s.bars,market),strategyName:definition.name,rule:describeMinuteRule(r.config),source:s.source,sampleKind:s.sample_kind,note:'在所示样本与参数下重新计算；不是券商成交。'});renderValidation(validation);info();}catch(e){status.textContent='未生成报告：'+e.message;}finally{button.disabled=false;}};
 return {select(m,t){market=m;type=t;for(const label of root.querySelectorAll('[data-adaptive]')){label.hidden=t!=='adaptive_momentum';label.querySelector('input').disabled=label.hidden;}form.elements.budget.value=m==='US'?2000:100000;form.elements.cost_bps.value={US:10,HK:20,CN:15}[m];form.elements.file.value='';root.querySelector('[data-lab-validation]').textContent='重新回测后显示固定参数的时间切分与成本检验。';info();}};
}
