import {sortStrategies} from './portfolio-ranking.mjs';
import {runReason} from './run-labels.mjs';
import {createExplanationUI} from './portfolio-explain-ui.mjs';
import {createReplayUI} from './replay-ui.mjs';
import {portfolioReplay} from './replay-model.mjs';
export function createPortfolioUI(root,api,chart,access=()=>false){
 const $=id=>root.querySelector('#'+id);
 let entries=[],selected=null,report=null,requestVersion=0;
 root.innerHTML=`<article class="panel"><p class="eyebrow">PORTFOLIO STRATEGIES</p><h2>① 选择市场和策略</h2><p>选策略 → 看历史回测 → 看最新选股 → 设置预算并启动模拟盘。股票由策略自动选择，你只需确定投入多少模拟资金。</p><div class="form-row"><label>市场<select id="pf-market"><option value="US">美股 · USD</option><option value="HK">港股 · HKD</option><option value="CN">A 股 · CNY</option></select></label><label>查找策略<input id="pf-search" type="search" placeholder="例如：动量、低波动、均线"></label><label>策略<select id="pf-strategy"></select></label><label>排列方式<select id="pf-sort"><option value="recommended">研究候选优先</option><option value="annual">历史年化收益更高</option><option value="drawdown">历史最大跌幅更小</option><option value="ratio">收益与回撤更均衡</option></select></label><label>可比较的回测范围<select id="pf-cohort"></select></label><button id="pf-refresh">刷新</button></div><p id="pf-search-note" class="caption" role="status"></p><p id="pf-capability" class="notice"></p><p class="caption">仅在同市场、同来源和同区间的报告内排序。收益回撤比 = 年化收益 ÷ 最大回撤绝对值；零回撤或缺失数据不参与该项排名。历史排名不是未来收益保证。</p><div id="pf-ranking" class="table-scroll strategy-ranking"></div></article>
 <article class="panel" id="pf-explanation"></article>
 <article class="panel"><h2>② 查看历史回测</h2><p>先看这套规则在过去的表现，再用下方回放查看当时选了哪些股票、何时买卖。历史选股不等于今天的选股。</p><h3 id="pf-title">历史回测</h3><label>回测来源<select id="pf-report-source"><option value="latest">当前股票池的历史回测</option><option value="reference">原始研究对照（股票池可能不同）</option></select></label><p id="pf-metrics"></p><div id="pf-chart" class="chart"></div><p class="caption">年化：把历史收益折算为每年；最大回撤：历史上从高点最多跌了多少。它们都不是收益承诺。</p><p id="pf-source" class="caption"></p><button id="pf-download">导出所选策略报告</button></article>
 <article class="panel"><h3>历史回放与逐日明细</h3><article id="pf-replay"></article></article>
 <article class="panel" id="pf-launch"><h2>④ 设置预算，开始模拟</h2><button id="pf-login" data-login>先登录，再设置模拟运行</button><p id="pf-signal-state">登录后查看信号和执行状态。</p><p>预算是新策略单独使用的模拟资金，原有股票不计入、不自动卖出。原有挂单尚未结束时，策略先等待；结束后再建立独立记账。启动后按最新信号自动选股、买卖，不需要手动挑股票。休市或行情过期时等待有效数据。同一市场一次运行一个策略；运行期间该市场的网页手动下单暂停开放。</p><details><summary>进阶：手动导入行情信号或回测文件</summary><label>选择信号 / 回测 JSON<input id="pf-file" type="file" accept="application/json,.json"></label><button id="pf-import">导入重放回测</button><button id="pf-upload">校验并保存最新信号</button></details><p id="pf-readiness" class="notice" role="status">正在读取启动条件…</p><button id="pf-open-orders" data-go="trade" data-focus="orders">核对该市场订单</button><div class="form-row"><label>模拟预算（所选市场币种）<input id="pf-budget" type="number" min="100" value="10000"></label><input id="pf-confirm" type="hidden" value="启动组合自动模拟交易"><button id="pf-start">确认开始模拟运行</button><button id="pf-resume">恢复原运行</button></div><div class="actions" id="pf-manage"><button id="pf-pause">暂停自动执行</button><button id="pf-tick">立即检查交易条件</button><button id="pf-release">结束已空仓的策略</button><button id="pf-keep">结束策略，保留股票</button></div><details id="pf-exit-panel"><summary>平仓并结束当前组合</summary><p>只卖出本策略买入的股票，保留启动前的原有持仓。按实时行情提交限价卖单，等待实际成交后停止。</p><label>输入“平仓并停止组合”<input id="pf-exit-confirm" autocomplete="off"></label><button id="pf-exit">授权自动平仓</button></details><p id="pf-message" role="status" aria-live="polite"></p></article>
 <article class="panel"><h2>⑤ 查看运行结果</h2><button data-go="runs">查看策略运行与历史记录</button><div id="pf-runs"></div><h3>调仓决策与订单意图</h3><div id="pf-decisions"></div><p class="caption">委托接收不等于成交。成交/撤单回报在左侧“手动交易与订单”中对应市场中核对。组合会按实际成交账本检查持仓偏差。</p></article>`;
 $('pf-market').closest('article').querySelector('.form-row').append($('pf-report-source').closest('label'));
 const explanation=createExplanationUI($('pf-explanation'),api,access,$('pf-budget'),text=>{$('pf-readiness').textContent=text;},$('pf-launch'),$('pf-market').closest('article'));
 // Latest targets follow historical research; budget and execution follow targets.
 root.insertBefore($('pf-explanation'),$('pf-launch'));
 const replay=createReplayUI($('pf-replay'),chart);replay.clear();
 for(const id of ['pf-import','pf-upload','pf-start','pf-resume','pf-pause','pf-tick','pf-release','pf-keep','pf-exit']){$(id).setAttribute('data-operator','');$(id).disabled=!access();}
 const node=(tag,text)=>{const e=document.createElement(tag);e.textContent=text;return e;};
 const message=(text,error=false)=>{$('pf-message').textContent=text;$('pf-message').classList.toggle('error',error);};
 async function action(button,fn){button.disabled=true;try{await fn();await status();}catch(e){message(e.message,true);}finally{button.disabled=!access()||button.dataset.unavailable==='1';}}
 function chooseMarket(selection){
 const marketEntries=entries.filter(e=>e.market===$('pf-market').value),groups=new Map();
 for(const e of marketEntries){const g=groups.get(e.cohort)||{rows:[],from:e.metrics?.from,to:e.metrics?.to};g.rows.push(e);groups.set(e.cohort,g);}
 const old=(typeof selection==='string'?marketEntries.find(e=>e.id===selection)?.cohort:null)||$('pf-cohort').value,ordered=[...groups].sort((a,b)=>(b[0]!=='missing')-(a[0]!=='missing')||b[1].rows.length-a[1].rows.length);
 $('pf-cohort').replaceChildren(...ordered.map(([key,g],i)=>{const o=node('option',key==='missing'?'暂无此来源回测':`${g.from} 至 ${g.to} · ${g.rows.length} 个策略 · 口径 ${i+1}`);o.value=key;return o;}));
 if(groups.has(old))$('pf-cohort').value=old;
 const all=sortStrategies(marketEntries.filter(e=>e.cohort===$('pf-cohort').value),$('pf-sort').value),query=$('pf-search').value.trim().toLowerCase(),rows=all.filter(e=>!query||e.name.toLowerCase().includes(query));
 $('pf-search-note').textContent=`当前比较范围 ${all.length} 个策略，搜索匹配 ${rows.length} 个；本市场共 ${marketEntries.length} 个。不同口径请切换比较范围。${all.some(e=>e.comparison_legacy)?' 旧导入报告按已存来源、股票池标识和区间分组，历史成本配置未独立留档，请以报告说明核对。':''}`;
 const table=document.createElement('table'),head=table.createTHead().insertRow();for(const name of ['策略名称','年化收益','最大回撤','收益回撤比','操作'])head.append(node('th',name));const body=table.createTBody();
 const value=(v,suffix='')=>v==null?'暂无':v.toFixed(2)+suffix;
 for(const e of rows){const tr=body.insertRow();for(const v of [e.name,value(e.metrics?.annual,'%'),value(e.metrics?.drawdown,'%'),value(e.metrics?.ratio)])tr.append(node('td',v));const td=node('td',''),button=node('button','查看策略');button.onclick=()=>{$('pf-strategy').value=e.id;choose();};td.append(button);tr.append(td);}
 $('pf-ranking').replaceChildren(table);
 if(!rows.length){$('pf-search-note').textContent+=' 没有匹配结果，请换个词。下方保留之前选中的策略。';return;}
 const previous=typeof selection==='string'?selection:$('pf-strategy').value;$('pf-strategy').replaceChildren(...rows.map(e=>{const o=node('option',(e.recommended?'研究候选 · ':'')+e.name);o.value=e.id;return o;}));if(rows.some(e=>e.id===previous))$('pf-strategy').value=previous;return choose();
 }
 async function choose(){selected=entries.find(e=>e.id===$('pf-strategy').value);if(!selected)return;const id=selected.id,version=++requestVersion;$('pf-open-orders').dataset.go=({CN:'cn-trade',US:'trade',HK:'longbridge'})[selected.market];report=null;explanation.load(id);replay.clear();$('pf-download').disabled=true;$('pf-title').textContent=selected.name;message('');$('pf-chart').replaceChildren();$('pf-metrics').textContent='读取回测…';$('pf-source').textContent='';for(const id of ['pf-start','pf-resume','pf-pause','pf-tick','pf-release','pf-keep','pf-exit']){$(id).disabled=true;$(id).dataset.unavailable='1';}
  $('pf-capability').textContent=selected.broker?`本策略使用 ${selected.currency} 模拟资金。后台更新日线信号，启动前会核对账户和交易条件。`:'当前策略仅支持历史研究，尚未提供自动执行适配器。';
  try{const r=await api('portfolio/report?id='+encodeURIComponent(id)+'&source='+$('pf-report-source').value);if(selected.id!==id||version!==requestVersion)return;report=r;replay.set(portfolioReplay(r));$('pf-download').disabled=false;$('pf-title').textContent=r.name;const m=r.report.full;$('pf-metrics').textContent=`年化 ${m.cagr_pct.toFixed(2)}% · 最大回撤 ${m.max_drawdown_pct.toFixed(2)}% · 累计 ${m.total_return_pct.toFixed(2)}%`;
   chart('pf-chart',r.report.dates.map((t,i)=>({t,equity:r.report.equity[i]})),[{key:'equity',name:'历史组合净值',color:'#527347'}],v=>v.toFixed(3));$('pf-source').textContent=r.source+'。'+r.report.dates[0]+' 至 '+r.report.dates.at(-1)+'；复权价格与可分割份额，实际模拟盘使用未复权报价、整手股数与成交回报。';await status();
  }catch(e){if(selected?.id!==id||version!==requestVersion)return;$('pf-metrics').textContent='暂无可显示的回测';$('pf-source').textContent=e.message+'。可切换至“原始研究对照”，或导入该策略的重放回测。';message(e.message,true);}
 }
 async function status(){$('pf-login').hidden=access();if(!access()){clear();return;}const expectedId=selected?.id,expectedMarket=$('pf-market').value;try{const s=await api('portfolio');if(selected?.id!==expectedId||$('pf-market').value!==expectedMarket)return;if(!access()){clear();return;}const market=$('pf-market').value,r=s.runs.find(r=>r.market===market),signal=s.signals.find(s=>s.strategy_id===selected?.id);const same=!!r&&r.strategy_id===selected?.id,fresh=!!signal&&Date.parse(signal.expires_at)>Date.now();for(const [id,allowed]of [['pf-start',!r&&fresh&&!!selected?.broker],['pf-resume',same&&!r.enabled],['pf-pause',same&&!!r.enabled],['pf-tick',same&&!!r.enabled],['pf-release',same&&!r.enabled],['pf-keep',same&&!r.enabled],['pf-exit',same]]){$(id).dataset.unavailable=allowed?'0':'1';$(id).disabled=!allowed;} $('pf-manage').hidden=!same;$('pf-resume').hidden=!same||!!r.enabled;$('pf-exit-panel').hidden=!same;$('pf-signal-state').textContent=signal?(fresh?'已准备好策略信号 · 日期：'+signal.signal_date+'。启动后仍会检查时效、交易时段和账户状态。':'当前信号已过期，暂不能开始新的模拟运行。请等待后台更新后点击“刷新”；历史回测仍可正常查看。'):'尚未准备好信号，请等待后台更新或联系维护者。';if(r?.ownership?.awaiting_orders)$('pf-signal-state').textContent+=' 正在等待原有订单结束，不会取消这些订单。';if(r)$('pf-signal-state').textContent+=' 当前市场由“'+(entries.find(e=>e.id===r.strategy_id)?.name||r.strategy_id)+'”管理，不能重复启动。';$('pf-runs').replaceChildren(...(s.runs.some(r=>r.market===market)?s.runs.filter(r=>r.market===market).map(r=>node('p',`${({CN:'A 股',US:'美股',HK:'港股'})[r.market]} · ${entries.find(e=>e.id===r.strategy_id)?.name||r.strategy_id} · 预算 ${r.budget} · ${r.enabled?'运行':'暂停'} · ${runReason(r.reason)} · ${r.updated_at}`)):[node('p','尚未启动组合') ]));$('pf-decisions').replaceChildren(...s.decisions.filter(d=>d.run_id===r?.run_id).slice(0,10).map(d=>{const box=document.createElement('details');box.append(node('summary',`${d.created_at} · ${d.phase} · ${d.payload.orders.length} 笔意图`),node('pre',JSON.stringify(d.payload.orders,null,2)));return box;}));}catch(e){clear();$('pf-signal-state').textContent=e.message;}}
 $('pf-report-source').onchange=async()=>{try{entries=(await api('portfolio/catalog?source='+$('pf-report-source').value)).strategies;await chooseMarket();}catch(e){message(e.message,true);}};$('pf-sort').onchange=()=>chooseMarket();$('pf-cohort').onchange=()=>chooseMarket();$('pf-market').onchange=()=>{$('pf-search').value='';chooseMarket();};let searchTimer;$('pf-search').oninput=()=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>chooseMarket(),250);};$('pf-strategy').onchange=choose;$('pf-refresh').onclick=()=>choose();
 $('pf-start').onclick=e=>action(e.currentTarget,async()=>{if(!confirm('启动 '+selected.name+'？预算 '+$('pf-budget').value+' '+selected.currency+'。确认后后台可提交模拟订单。'))return;await api('portfolio/start',{strategy_id:selected.id,budget:Number($('pf-budget').value),confirm:$('pf-confirm').value});message('已授权；后台将按最新信号和账户状态执行。');});
 for(const name of ['pause','tick','resume','release'])$('pf-'+name).onclick=e=>action(e.currentTarget,async()=>{const r=await api('portfolio/'+name,{market:$('pf-market').value,confirm:$('pf-confirm').value});message(r.message||(r.outcome?runReason(r.outcome):'操作完成，状态已刷新。'));});
 $('pf-keep').onclick=e=>action(e.currentTarget,async()=>{if(!confirm('结束这个策略并保留现有股票？策略将停止管理，这些股票转为手动持仓。新策略会将它们视为原有持仓，不自动卖出。'))return;await api('portfolio/release',{market:$('pf-market').value,keep_positions:true,confirm:'结束策略并保留持仓'});message('策略已结束；股票仍在账户中，可到手动交易页管理，也可以选择新策略。');});
 $('pf-exit').onclick=e=>action(e.currentTarget,async()=>{await api('portfolio/liquidate',{market:$('pf-market').value,confirm:$('pf-exit-confirm').value});message('已授权按实时行情平仓，请跟踪实际成交。');});
 $('pf-import').onclick=e=>action(e.currentTarget,async()=>{const file=$('pf-file').files[0];if(!file||file.size>2000000)throw Error('请选择小于 2 MB 的研究输出文件');const data=JSON.parse(await file.text());if(data.signal?.strategy_id!==selected.id)throw Error('文件策略与当前选择不一致');await api('portfolio/backtests',data);$('pf-report-source').value='latest';await choose();message('已导入重放回测；未启动交易。');});
 $('pf-upload').onclick=e=>action(e.currentTarget,async()=>{const file=$('pf-file').files[0];if(!file||file.size>2000000)throw Error('请选择小于 2 MB 的研究输出文件');const data=JSON.parse(await file.text()),signal=data.signal||data;if(signal.strategy_id!==selected.id)throw Error('文件策略与当前选择不一致');await api('portfolio/signals',signal);message('信号已校验保存；未启动交易。');});
 $('pf-download').onclick=()=>{if(!report)return;const url=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=selected.id.replaceAll(':','_')+'.json';a.click();URL.revokeObjectURL(url);};
 function clear(){explanation.clearAccount();$('pf-login').hidden=access();for(const id of ['pf-start','pf-resume','pf-pause','pf-tick','pf-release','pf-keep','pf-exit']){$(id).disabled=true;$(id).dataset.unavailable='1';}$('pf-manage').hidden=true;$('pf-resume').hidden=true;$('pf-exit-panel').hidden=true;$('pf-runs').replaceChildren();$('pf-decisions').replaceChildren();$('pf-signal-state').textContent='登录后查看执行状态';}
 return {clear,async load(selection){try{if(selection){if(!entries.length)entries=(await api('portfolio/catalog?source='+$('pf-report-source').value)).strategies;$('pf-search').value='';$('pf-market').value=selection.split(':')[0];await chooseMarket(selection);return;}if(!entries.length){entries=(await api('portfolio/catalog?source='+$('pf-report-source').value)).strategies;await chooseMarket();}else await choose();}catch(e){message(e.message,true);}}};
}
