export function createPortfolioUI(root,api,chart,access=()=>false){
 const $=id=>root.querySelector('#'+id);
 let entries=[],selected=null,report=null,requestVersion=0;
 root.innerHTML=`<article class="panel"><p class="eyebrow">PORTFOLIO STRATEGIES</p><h2>组合回测与自动模拟盘</h2><p>三市场组合使用统一的逐日决策规则。选择策略查看历史回测；发布最新完整日线信号后，可授权对应模拟账户自动调仓。</p><div class="form-row"><label>市场<select id="pf-market"><option value="US">美股 · USD</option><option value="HK">港股 · HKD</option><option value="CN">A 股 · CNY</option></select></label><label>策略<select id="pf-strategy"></select></label><button id="pf-refresh">刷新</button></div><p id="pf-capability" class="notice"></p><p>其他已保留策略：<button data-go="research">单标的与分钟策略回测</button> <button data-go="library">历史分钟研究</button> <button data-go="longbridge">长桥定投执行</button></p></article>
 <article class="panel"><h3 id="pf-title">历史回测</h3><label>回测来源<select id="pf-report-source"><option value="reference">仓库历史研究</option><option value="latest">最新导入的重放回测</option></select></label><p id="pf-metrics"></p><div id="pf-chart" class="chart"></div><p id="pf-source" class="caption"></p><button id="pf-download">导出所选策略报告</button></article>
 <article class="panel"><h3>信号与自动执行</h3><p id="pf-signal-state">登录后查看信号和执行状态。</p><p>首次启动要求该市场账户空仓。预算以本市场币种计价，委托仍受券商页的单笔/当日限额约束。缺少最新日线、有效交易时段或实时报价时等待，不使用历史报告下单。</p><label>上传由 portfolio_signal.py 生成的信号/回测 JSON<input id="pf-file" type="file" accept="application/json,.json"></label><button id="pf-import">导入重放回测</button><button id="pf-upload">校验并保存最新信号</button><div class="form-row"><label>策略预算<input id="pf-budget" type="number" min="100" value="10000"></label><label>输入“启动组合自动模拟交易”<input id="pf-confirm" autocomplete="off"></label><button id="pf-start">授权启动所选策略</button><button id="pf-resume">恢复原运行</button></div><div class="actions"><button id="pf-pause">暂停自动执行</button><button id="pf-tick">检查一轮</button><button id="pf-release">空仓后释放管理权</button></div><details><summary>平仓并结束当前组合</summary><p>按实时行情提交限价卖单，等待实际成交后停止。卖单未成交不会视为平仓完成。</p><label>输入“平仓并停止组合”<input id="pf-exit-confirm" autocomplete="off"></label><button id="pf-exit">授权自动平仓</button></details><p id="pf-message" role="status" aria-live="polite"></p></article>
 <article class="panel"><h3>运行记录</h3><div id="pf-runs"></div><h3>调仓决策与订单意图</h3><div id="pf-decisions"></div><p class="caption">委托接收不等于成交。成交/撤单回报在美股“模拟交易”或“港股 · 长桥”中核对。组合会按实际成交账本检查持仓偏差。</p></article>`;
 for(const id of ['pf-import','pf-upload','pf-start','pf-resume','pf-pause','pf-tick','pf-release','pf-exit']){$(id).setAttribute('data-operator','');$(id).disabled=!access();}
 const node=(tag,text)=>{const e=document.createElement(tag);e.textContent=text;return e;};
 const message=(text,error=false)=>{$('pf-message').textContent=text;$('pf-message').classList.toggle('error',error);};
 async function action(button,fn){button.disabled=true;try{await fn();await status();}catch(e){message(e.message,true);}finally{button.disabled=!access()||button.dataset.unavailable==='1';}}
 function chooseMarket(){const rows=entries.filter(e=>e.market===$('pf-market').value).sort((a,b)=>Number(b.recommended)-Number(a.recommended));$('pf-strategy').replaceChildren(...rows.map(e=>{const o=node('option',(e.recommended?'当前候选 · ':'')+e.name);o.value=e.id;return o;}));choose();}
 async function choose(){selected=entries.find(e=>e.id===$('pf-strategy').value);if(!selected)return;const id=selected.id,version=++requestVersion;report=null;$('pf-chart').replaceChildren();$('pf-metrics').textContent='读取回测…';$('pf-source').textContent='';
  $('pf-capability').textContent=selected.broker?`${selected.currency} · ${selected.broker} 模拟盘 · ${selected.version}。需配置后台调度与最新行情/信号生产器。`:'A 股历史回测可用；自动下单接口已预留，尚无已连接券商，不能启动。';$('pf-start').dataset.unavailable=selected.broker?'0':'1';$('pf-start').disabled=!access()||!selected.broker;
  try{const r=await api('portfolio/report?id='+encodeURIComponent(id)+'&source='+$('pf-report-source').value);if(selected.id!==id||version!==requestVersion)return;report=r;$('pf-title').textContent=r.name;const m=r.report.full;$('pf-metrics').textContent=`年化 ${m.cagr_pct.toFixed(2)}% · 最大回撤 ${m.max_drawdown_pct.toFixed(2)}% · 累计 ${m.total_return_pct.toFixed(2)}%`;
   chart('pf-chart',r.report.dates.map((t,i)=>({t,equity:r.report.equity[i]})),[{key:'equity',name:'历史组合净值',color:'#527347'}],v=>v.toFixed(3));$('pf-source').textContent=r.source+'。'+r.report.dates[0]+' 至 '+r.report.dates.at(-1)+'；复权价格与可分割份额，实际模拟盘使用未复权报价、整手股数与成交回报。';await status();
  }catch(e){message(e.message,true);}
 }
 async function status(){try{const s=await api('portfolio');if(!access()){clear();return;}const market=$('pf-market').value,r=s.runs.find(r=>r.market===market),signal=s.signals.find(s=>s.strategy_id===selected?.id);$('pf-signal-state').textContent=signal?'已发布信号日期：'+signal.signal_date:'尚未发布所选策略的完整日线信号。';$('pf-runs').replaceChildren(...(s.runs.length?s.runs.map(r=>node('p',`${r.market} · ${r.strategy_id} · 预算 ${r.budget} · ${r.enabled?'运行':'暂停'} · ${r.reason} · ${r.updated_at}`)):[node('p','尚未启动组合') ]));$('pf-decisions').replaceChildren(...s.decisions.filter(d=>d.run_id===r?.run_id).slice(0,10).map(d=>{const box=document.createElement('details');box.append(node('summary',`${d.created_at} · ${d.phase} · ${d.payload.orders.length} 笔意图`),node('pre',JSON.stringify(d.payload.orders,null,2)));return box;}));}catch(e){clear();$('pf-signal-state').textContent=e.message;}}
 $('pf-report-source').onchange=choose;$('pf-market').onchange=chooseMarket;$('pf-strategy').onchange=choose;$('pf-refresh').onclick=()=>choose();
 $('pf-start').onclick=e=>action(e.currentTarget,async()=>{await api('portfolio/start',{strategy_id:selected.id,budget:Number($('pf-budget').value),confirm:$('pf-confirm').value});message('已授权；后台将按最新信号和账户状态执行。');});
 for(const name of ['pause','tick','resume','release'])$('pf-'+name).onclick=e=>action(e.currentTarget,async()=>{const r=await api('portfolio/'+name,{market:$('pf-market').value,confirm:$('pf-confirm').value});message(r.message||r.outcome||'操作完成，状态已刷新。');});
 $('pf-exit').onclick=e=>action(e.currentTarget,async()=>{await api('portfolio/liquidate',{market:$('pf-market').value,confirm:$('pf-exit-confirm').value});message('已授权按实时行情平仓，请跟踪实际成交。');});
 $('pf-import').onclick=e=>action(e.currentTarget,async()=>{const file=$('pf-file').files[0];if(!file||file.size>2000000)throw Error('请选择小于 2 MB 的研究输出文件');const data=JSON.parse(await file.text());if(data.signal?.strategy_id!==selected.id)throw Error('文件策略与当前选择不一致');await api('portfolio/backtests',data);$('pf-report-source').value='latest';await choose();message('已导入重放回测；未启动交易。');});
 $('pf-upload').onclick=e=>action(e.currentTarget,async()=>{const file=$('pf-file').files[0];if(!file||file.size>2000000)throw Error('请选择小于 2 MB 的研究输出文件');const data=JSON.parse(await file.text()),signal=data.signal||data;if(signal.strategy_id!==selected.id)throw Error('文件策略与当前选择不一致');await api('portfolio/signals',signal);message('信号已校验保存；未启动交易。');});
 $('pf-download').onclick=()=>{if(!report)return;const url=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=selected.id.replaceAll(':','_')+'.json';a.click();URL.revokeObjectURL(url);};
 function clear(){$('pf-runs').replaceChildren();$('pf-decisions').replaceChildren();$('pf-signal-state').textContent='登录后查看执行状态';}
 return {clear,async load(selection){try{if(selection){if(!entries.length)entries=(await api('portfolio/catalog')).strategies;$('pf-market').value=selection.split(':')[0];chooseMarket();$('pf-strategy').value=selection;await choose();return;}if(!entries.length){entries=(await api('portfolio/catalog')).strategies;chooseMarket();}else await choose();}catch(e){message(e.message,true);}}};
}
