import {replayAt,eventIndices,reportHTML} from './replay-model.mjs';
let serial=0;
export function createReplayUI(root,chart){
 const id='replay-'+(++serial),$=name=>root.querySelector('[data-replay="'+name+'"]');let model=null,index=0,timer=null,events=[],downloadURL=null;
 root.classList.add('replay-workbench');root.hidden=true;
 root.innerHTML=`<div class="panel-head"><div><p class="eyebrow">HISTORICAL REPLAY / 历史回放</p><h2 data-replay="title"></h2></div><button data-replay="export">导出课堂报告 HTML</button><a data-replay="download" hidden>报告已生成 · 点击保存</a></div><p data-replay="source" class="notice"></p><p class="caption">全样本策略总览 · 以下指标不随观察时点变化</p><div data-replay="metrics" class="mini-metrics"></div><details><summary>策略规则与回测假设</summary><p data-replay="rules"></p><pre data-replay="config"></pre></details><div class="replay-charts"><div><h3>累计净值 · 截至选定时点</h3><div id="${id}-equity" class="chart"></div></div><div><h3>回撤走势</h3><div id="${id}-drawdown" class="chart"></div></div></div><div class="replay-controls"><button data-replay="start">回到起点</button><button data-replay="prev">上一时点</button><button data-replay="play">自动播放</button><button data-replay="next">下一时点</button><button data-replay="event">下一笔成交 / 调仓</button><button data-replay="end">查看完整结果</button><label>跳至日期<input data-replay="date" type="date"></label></div><label class="replay-slider">历史时间轴<input data-replay="slider" type="range" min="0" step="1" value="0"></label><p data-replay="time" class="replay-time" aria-live="polite"></p><div class="replay-decision"><h3>这个时间点发生了什么</h3><p data-replay="decision"></p><p data-replay="position"></p><p data-replay="fills"></p></div><details><summary>查看全部成交时间线</summary><div data-replay="timeline" class="replay-timeline"></div></details><p class="caption">时间按行情原始时间显示（Z 为 UTC）；滑块只改变观察时点，不重新优化参数。绿色为策略，蓝色为原报告基准。收盘决策用于随后可执行时点，与本时点已发生的成交分开显示。</p>`;
 const fmt=n=>Number.isFinite(n)?n.toLocaleString('zh-CN',{maximumFractionDigits:3}):'未记录',pct=n=>Number.isFinite(n)?(n*100).toFixed(2)+'%':'未记录';
 function stop(){clearInterval(timer);timer=null;$('play').textContent='自动播放';}
 function draw(){if(!model?.points.length)return;const {point,decision,trades}=replayAt(model,index);$('slider').value=index;$('date').value=point.t.slice(0,10);$('time').textContent=`${point.t} · ${index+1} / ${model.points.length} 个观测点 · 净值 ${fmt(point.equity)} ${model.currency} · 回撤 ${pct(point.drawdown)}`;
  $('decision').textContent=decision?'收盘决策：'+decision.reason+(Number.isFinite(decision.value)?'；规则参考值 '+fmt(decision.value):''):'未保存本时点的决策记录；只能核对净值，不能据此判断当日选股或交易原因。';
  $('position').textContent=decision?.targets?'收盘目标权重（尚非成交持仓）：'+(decision.targets.map(t=>t.symbol+' '+pct(t.weight)).join('、')||'无股票目标')+'；现金目标 '+pct(1-decision.targets.reduce((a,t)=>a+t.weight,0))+(decision.holdings?.length?'。回测实际持仓：'+decision.holdings.map(h=>h.symbol+' '+fmt(h.qty)+' 份').join('、'):'')+(Number.isFinite(decision.cash)?'；账面现金 '+fmt(decision.cash):''):(decision?'收盘持仓 '+fmt(decision.qty)+' 股 · 现金 '+fmt(decision.cash)+' '+model.currency+' · 收盘价 '+fmt(decision.price):'');
  $('fills').textContent=trades.length?'本时点回测成交：'+trades.map(t=>(t.side==='buy'?'买入':'卖出')+' '+(t.symbol||'')+' '+fmt(t.qty)+' 股 @ '+fmt(t.price)+'；成本 '+fmt(t.cost)+'；'+(t.signal_t?'依据 '+t.signal_t+' 的信号':t.reason||'原报告未保存信号时间')).join('。'):model.trades.length?'本时点没有回测成交。':'此报告无逐笔成交明细。';
  const points=model.points.slice(0,index+1);chart(id+'-equity',points,[{key:'equity',name:'策略',color:'#527347'},{key:'benchmark',name:'基准',color:'#627d9b'}],fmt);chart(id+'-drawdown',points,[{key:'drawdown',name:'回撤',color:'#b44b45'}],pct);
  $('prev').disabled=index===0;$('next').disabled=index===model.points.length-1;$('event').disabled=!events.some(i=>i>index);
 }
 function seek(n){stop();index=Math.max(0,Math.min(model.points.length-1,n));draw();}
 $('slider').oninput=()=>seek(Number($('slider').value));$('prev').onclick=()=>seek(index-1);$('next').onclick=()=>seek(index+1);$('start').onclick=()=>seek(0);$('end').onclick=()=>seek(model.points.length-1);$('event').onclick=()=>seek(events.find(i=>i>index)??index);
 $('date').onchange=()=>{const i=model.points.findIndex(p=>p.t.slice(0,10)>=$('date').value);seek(i<0?model.points.length-1:i);};
 $('play').onclick=()=>{if(timer){stop();return;}if(index===model.points.length-1)index=0;$('play').textContent='暂停';draw();timer=setInterval(()=>{if(!root.getClientRects().length||document.hidden||index>=model.points.length-1){stop();return;}index++;draw();},650);};
 $('export').onclick=()=>{const old=index;index=model.points.length-1;draw();const markup=root.querySelector('#'+id+'-equity').innerHTML+root.querySelector('#'+id+'-drawdown').innerHTML;index=old;draw();if(downloadURL)URL.revokeObjectURL(downloadURL);downloadURL=URL.createObjectURL(new Blob([reportHTML(model,markup)],{type:'text/html;charset=utf-8'}));const a=$('download');a.href=downloadURL;a.download='策略课堂报告.html';a.hidden=false;a.click();};
 return {clear(){stop();model=null;root.hidden=true;},set(value){stop();if(downloadURL){URL.revokeObjectURL(downloadURL);downloadURL=null;}$('download').hidden=true;model=value;root.hidden=!model.points.length;if(root.hidden)return;events=eventIndices(model);index=model.points.length-1;$('title').textContent=model.title;$('source').textContent=(model.kind==='synthetic'?'合成演示样本 · 非真实历史收益':'历史数据回测')+' · '+model.source+' · '+model.points[0].t+' 至 '+model.points.at(-1).t;
 $('rules').textContent=model.rules.join(' ');$('config').textContent=JSON.stringify(model.config||{},null,2);$('metrics').replaceChildren(...[['累计收益',pct(model.returnRate)],['最大回撤',pct(model.drawdown)],['回测成交',model.tradeCount==null?'未保存笔数':model.tradeCount+' 笔'],['初始资金 / 净值',fmt(model.capital)+' '+model.currency],['累计成本'+(model.costCurrency?' · '+model.costCurrency:''),fmt(model.cost)],['记录完整度',model.decisions.length===model.points.length?'逐时点决策':'净值 / 部分决策']].map(([k,v])=>{const d=document.createElement('div'),label=document.createElement('span'),b=document.createElement('strong');label.textContent=k;b.textContent=v;d.append(label,b);return d;}));$('slider').max=model.points.length-1;$('date').min=model.points[0].t.slice(0,10);$('date').max=model.points.at(-1).t.slice(0,10);
 $('timeline').replaceChildren(...model.trades.map(t=>{const b=document.createElement('button');b.textContent=t.t+' · '+(t.side==='buy'?'买入':'卖出')+' '+t.qty+' 股';b.onclick=()=>seek(model.points.findIndex(p=>p.t>=t.t));return b;}));draw();}};
}
