export function engineReplay(r){
 return {title:r.config?.name||'策略回测',source:r.data_source||'已保存回测',kind:r.sampleKind||'historical',rules:r.limitations||[],config:r.config,points:r.curve||[],decisions:r.decisions||[],trades:r.trades||[],tradeCount:r.metrics?.trade_count,capital:100000,currency:'USD',returnRate:r.metrics?.total_return,drawdown:r.metrics?.max_drawdown,cost:r.metrics?.total_cost};
}
export function minuteReplay(r){return {validation:r.validation,title:r.strategyName+' · '+r.symbol,source:r.source,kind:r.sampleKind,rules:[r.rule,...(r.dataQuality?[`原始 ${r.dataQuality.received} 根；排除非连续交易时段 ${r.dataQuality.outside_session} 根。参考缺口：${r.dataQuality.sessions.map(d=>d.date+' '+d.reference_missing+' 根').join('；')}。${r.dataQuality.note}`]:[]),`单边成本 ${r.costBps} 基点；${r.tplus?'T+1，次日开盘退出':'收盘前 15 分钟发出退出信号；美股样本末根收盘强制退出，港股末根开盘退出'}。`,r.note,'美股与参数化回测共用引擎；相同样本与参数下，信号、成交和账户收益一致。港股/A 股遵守各自市场结算规则。'],config:{...r.config,market:r.market},points:r.equityCurve,decisions:r.decisions||[],trades:r.orders,tradeCount:r.orders.length,capital:r.initialCapital??r.budget,currency:r.currency,returnRate:r.net/(r.initialCapital??r.budget),drawdown:r.maxDrawdown,cost:r.totalCost};}
export function portfolioReplay(r){let peak=1;return {title:r.name,source:r.source,kind:'historical',rules:['收盘确定目标，下一交易日开盘执行；复权价格、可分割份额。',r.report.decisions?.length?'该报告包含决策内核输出的逐日目标；实际持仓与回测成交分别记录。':'旧研究仅有净值存档；没有记录的选股原因与成交明细不会由曲线反推。'],config:r.config,points:r.report.dates.map((t,i)=>{const equity=r.report.equity[i];peak=Math.max(peak,equity);return {t,equity,drawdown:equity/peak-1};}),decisions:r.report.decisions||[],trades:r.report.trades||[],tradeCount:r.report.trade_count,cost:r.report.cost,costCurrency:r.currency,capital:1,currency:'净值',returnRate:r.report.full.total_return_pct/100,drawdown:r.report.full.max_drawdown_pct/100};}
export function replayAt(model,index){
 const p=model.points[index];if(!p)return null;
 return {point:p,decision:model.decisions.find(d=>d.t===p.t)||null,trades:model.trades.filter(t=>t.t===p.t)};
}
export function eventIndices(model){const times=new Set(model.trades.map(t=>t.t));return model.points.flatMap((p,i)=>times.has(p.t)||model.decisions.find(d=>d.t===p.t)?.rebalanced?[i]:[]);}
export const escapeHTML=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function reportHTML(model,chartMarkup){
 const e=escapeHTML,pct=n=>Number.isFinite(n)?(n*100).toFixed(2)+'%':'未记录';
 const rows=model.decisions.map(d=>`<tr><td>${e(d.t)}</td><td>${e(d.reason)}</td><td>${e(d.qty??'—')}</td><td>${e(d.cash??'—')}</td><td>${e(d.targets?d.targets.map(t=>t.symbol+' '+pct(t.weight)).join('、'):'—')}</td></tr>`).join('');
 return `<!doctype html><html lang="zh-CN"><meta charset="utf-8"><title>${e(model.title)}</title><style>body{font:15px system-ui;color:#30372b;background:#fffdf2;max-width:1100px;margin:40px auto;padding:24px}svg{width:100%;height:auto}table{border-collapse:collapse;width:100%}td,th{padding:8px;border-bottom:1px solid #ddd;text-align:left}p{line-height:1.8}@media print{body{margin:0}tr{break-inside:avoid}}</style><h1>${e(model.title)}</h1><p>${model.kind==='synthetic'?'合成样本 · 不用于评价历史表现':'历史数据回测 · 非券商成交'}</p><p>${e(model.source)}<br>${e(model.points[0]?.t)} 至 ${e(model.points.at(-1)?.t)}</p><p>累计收益 ${pct(model.returnRate)} · 最大回撤 ${pct(model.drawdown)} · 回测成交 ${e(model.tradeCount??'未记录')} 笔（无明细不代表没有交易）</p><p>${model.rules.map(e).join('<br>')}</p><pre>${e(JSON.stringify(model.config||{},null,2))}</pre>${chartMarkup}${model.validation?'<h2>时间切分与成本检验</h2><p>'+e(model.validation.status)+'</p><table><tr><th>情景</th><th>交易日</th><th>收益</th><th>最大回撤</th></tr>'+[['full','完整样本'],['development','前60%开发段'],['holdout','后40%检验段'],['double_cost','双倍成本']].map(([k,label])=>{const v=model.validation[k];return '<tr><td>'+label+'</td><td>'+e(v?.days??'未计算')+'</td><td>'+e(v?.return_pct?.toFixed(3)??'—')+'%</td><td>'+e(v?.drawdown_pct?.toFixed(3)??'—')+'%</td></tr>';}).join('')+'</table>':''}<h2>逐时点决策记录</h2>${rows?'<table><tr><th>时间</th><th>决策</th><th>股数</th><th>现金</th><th>收盘目标权重</th></tr>'+rows+'</table>':'<p>此报告未保存逐时点决策；仅展示历史净值。</p>'}<h2>回测成交</h2><table><tr><th>成交时间</th><th>信号时间</th><th>方向</th><th>数量</th><th>价格</th><th>成本</th></tr>${model.trades.map(t=>'<tr>'+[t.t,t.signal_t||'未记录',t.side==='buy'?'买入':'卖出',t.qty,t.price,t.cost].map(v=>'<td>'+e(v)+'</td>').join('')+'</tr>').join('')}</table></html>`;
}
