import {cp,mkdir,rm} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {resolve} from 'node:path';
import './build-library-demo.mjs';
import './bundle.mjs';
const root=fileURLToPath(new URL('..',import.meta.url)),dist=resolve(root,'dist');
await rm(dist,{recursive:true,force:true});
await mkdir(resolve(dist,'server'),{recursive:true});
await mkdir(resolve(dist,'.openai'),{recursive:true});
await cp(resolve(root,'worker/index.js'),resolve(dist,'server/index.js'));
await cp(resolve(root,'.openai/hosting.json'),resolve(dist,'.openai/hosting.json'));
await cp(resolve(root,'drizzle'),resolve(dist,'.openai/drizzle'),{recursive:true});
console.log('Built dist (portable Node build).');
